language: c
os: linux

env:
  global:
    - RACKET_DIR=~/racket

  # each "-" after "jobs:" starts a new job;
  # maximum travis-ci runtime/job = 50 min
  # 2 max cores(?) per job?
  #
  # not possible to use nested env values to construct a build matrix:
  # https://stackoverflow.com/questions/46575415/can-i-multiply-options-in-matrix-include-with-the-env-option
  # https://github.com/travis-ci/travis-ci/issues/1519
  jobs:
    - NAME="Turnstile+"      RACKET_VERSION="7.0"
    - NAME="Turnstile+"      RACKET_VERSION="7.5"
    - NAME="Cur"             RACKET_VERSION="7.0"
    - NAME="Cur"             RACKET_VERSION="7.5"
    - NAME="SBPV Scheme"     RACKET_VERSION="7.0"
    - NAME="SBPV Scheme"     RACKET_VERSION="7.5"
    - NAME="Typed Syndicate" RACKET_VERSION="7.0"
    - NAME="Typed Syndicate" RACKET_VERSION="7.5"

# matrix:
#   allow_failures:
#     - env: RACKET_VERSION="HEAD"

before_install:
  # install Racket
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  # install Turnstile+
  - git clone https://github.com/stchang/macrotypes.git
  - raco pkg install --auto -j 2 macrotypes/macrotypes-lib/
  - raco pkg install --auto -j 2 macrotypes/turnstile-lib/
  - raco pkg install --auto -j 2 macrotypes/rackunit-macrotypes-lib/

install:
  - chmod +x ./install.sh
  - ./install.sh

script:
  - chmod +x ./run-tests.sh
  - ./run-tests.sh
  - raco setup -j 2

#       before_install: # install Racket
#       - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
#       - cat ../travis-racket/install-racket.sh | bash
#       - export PATH="${RACKET_DIR}/bin:${PATH}"
#       install:
#       # install Turnstile+
#       - git clone https://github.com/stchang/macrotypes.git
#       - raco pkg install --auto -j 2 macrotypes/macrotypes-lib/
#       - raco pkg install --auto -j 2 macrotypes/turnstile-lib/
#       - raco pkg install --auto -j 2 macrotypes/rackunit-macrotypes-lib/
#       - raco pkg install --auto -j 2 macrotypes/macrotypes-example/
#       - raco pkg install --auto -j 2 macrotypes/turnstile-example/
#       - raco pkg install --auto -j 2 macrotypes/macrotypes-test/
#       - raco pkg install --auto -j 2 macrotypes/turnstile-test/
#       script:
#       - raco test -j 2 --package macrotypes-test
#       - raco test -j 2 --package turnstile-test
#       - raco setup -j 2

#     - if: env(JOBNAME) = "Cur"
#       before_install: # install Racket
#       - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
#       - cat ../travis-racket/install-racket.sh | bash
#       - export PATH="${RACKET_DIR}/bin:${PATH}"
#       install:
#       # install Turnstile+
#       - git clone https://github.com/stchang/macrotypes.git
#       - raco pkg install --auto -j 2 macrotypes/macrotypes-lib/
#       - raco pkg install --auto -j 2 macrotypes/turnstile-lib/
#       - raco pkg install --auto -j 2 macrotypes/rackunit-macrotypes-lib/
#       # install Cur
#       - git clone -b popl2020-artifact https://github.com/stchang/cur.git
#       - raco pkg install --auto -j 2 cur/cur-lib/
#       - raco pkg install --auto -j 2 cur/cur-test/
#       script:
#       - raco test --package cur-test
#       - raco setup -j 2

#     - if: env(JOBNAME) = "CBPV Scheme"
#       before_install: # install Racket
#       - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
#       - cat ../travis-racket/install-racket.sh | bash
#       - export PATH="${RACKET_DIR}/bin:${PATH}"
#       install:
#       # install Turnstile+
#       - git clone https://github.com/stchang/macrotypes.git
#       - raco pkg install --auto -j 2 macrotypes/macrotypes-lib/
#       - raco pkg install --auto -j 2 macrotypes/turnstile-lib/
#       - raco pkg install --auto -j 2 macrotypes/rackunit-macrotypes-lib/
#       # install CBPV Scheme
#       - git clone https://github.com/maxsnew/modal-scheme.git
#       - raco pkg install --auto -j 2 modal-scheme/sbpv/
#       script:
#       - raco test -j 2 --package sbpv
#       - raco test -j 2 --timeout 200 modal-scheme/examples/
#       - raco setup -j 2

#     - if: env(JOBNAME) = "Typed Syndicate"
#       before_install: # install Racket
#       - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
#       - cat ../travis-racket/install-racket.sh | bash
#       - export PATH="${RACKET_DIR}/bin:${PATH}"
#       install:
#       # install Turnstile+
#       - git clone https://github.com/stchang/macrotypes.git
#       - raco pkg install --auto -j 2 macrotypes/macrotypes-lib/
#       - raco pkg install --auto -j 2 macrotypes/turnstile-lib/
#       - raco pkg install --auto -j 2 macrotypes/rackunit-macrotypes-lib/
#       # install Typed Syndicate
#       - git clone -b behav https://github.com/tonyg/syndicate.git
#       - raco pkg install --auto -j 2 -n syndicate syndicate/racket/
#       script:
#       - raco test -j 2 syndicate/racket/typed/
#       - raco setup -j 2
