language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="7.0"
    - RACKET_VERSION="7.1"
    - RACKET_VERSION="7.2"
    - RACKET_VERSION="7.3"
    - RACKET_VERSION="7.4"
    - RACKET_VERSION="7.5"
    - RACKET_VERSION="HEAD"
matrix:
  allow_failures:
    - env: RACKET_VERSION="HEAD"

# maximum travis-ci runtime = 50 min
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
 # Turnstile+
 - git clone https://github.com/stchang/macrotypes.git
 - raco pkg install --auto -j 4 macrotypes/macrotypes-lib/
 - raco pkg install --auto -j 4 macrotypes/macrotypes-example/
 - raco pkg install --auto -j 4 macrotypes/rackunit-macrotypes-lib/
 - raco pkg install --auto -j 4 macrotypes/macrotypes-test/
 - raco pkg install --auto -j 4 macrotypes/turnstile-lib/
 - raco pkg install --auto -j 4 macrotypes/turnstile-example/
 - raco pkg install --auto -j 4 macrotypes/turnstile-test/
 # Cur
 - git clone -b popl2020-artifact https://github.com/stchang/cur.git
 - raco pkg install --auto -j 4 cur/cur-lib/
 - raco pkg install --auto -j 4 cur/cur-test/
 # CBPV Scheme
 - git clone https://github.com/maxsnew/modal-scheme.git
 - raco pkg install --auto -j 4 modal-scheme/sbpv/
 # Typed Syndicate
 - git clone -b behav https://github.com/tonyg/syndicate.git
 - raco pkg install --auto -j 4 -n syndicate syndicate/racket/

script:
 - raco test -j 4 --package macrotypes-test
 - raco test -j 4 --package turnstile-test
 - raco test -j 4 --timeout 200 --package cur-test
 - raco test -j 4 --package sbpv
 - raco test -j 4 --timeout 200 modal-scheme/examples/
 - raco test -j 4 syndicate/racket/typed/
 - raco setup -j 4
